### ISSUE TITLE
Cleanup of Gammapy-data

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy-data#41]
This lists some proposals for cleanup of gammapy data. There are some confusing/unreadable files that might be better to remove.

- [x] 1. Add another lightcurve with at least 2 bins in energy i.e. in `estimators/pks2155_hess_lc/`  #75
- [x]  2. Background files in `tests/irf/` lack energy units. leads to `UnitConversionError`. There is in fact a TODO in `/gammapy/makers/tests/test_map.py:520` to create a better example file.  #77
- [x] 3.  Remove `model.xml` in `tests/models/light_curve` #73
- [x]  4. Remove xml files in `tests/models`. Also remove the gc fits files in same location. These files are not used, and relevant files already exist #73
- [x]  5. Inconsistency between column & header names in 1es0229_hess_spectrum `tests/spectrum/flux_points`. The README says these files were downloaded from the GADF, but the referenced GADF link does not exist any more. Remove files. #73
- [x]  6. The stat_scan values in `tests/spectrum/flux_points/binlike.fits` are not compatible with the results. Remove? This is used in the docstring for `FluxPoints.recompute_ul` but can be replaced by the examples in estimators #73
- [ ] 7. The data available in `tests/unbundled/tev_spectra` can be useful. The are presently unused, but it may be useful to document this somewhere (in gammapy.astro maybe). Or, we can remove it...

This is separate from the issue of the catalogs we can provide (ie, all fermi catalogs or only the latest one, etc)

If this sounds okay, I can do the cleanup. Opinions @registerrier @QRemy @bkhelifi @MRegeard @Astro-Kirsty @adonath

**Comment by Astro-Kirsty** [comment]
Thanks @AtreyeeS. The list looks good to me!
